### Check response status, headers, and content-type
GET http://localhost:8080/get

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Headers option exists", function() {
        client.assert(response.body.hasOwnProperty("headers"), "Cannot find 'headers' option in response");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

###
GET http://localhost:8080/json


###
GET http://localhost:8080/cookies
Cookie: hello=world


###
GET https://localhost:8443/httpbin/headers
Custom-header: hello=world

###
GET http://localhost:8080/redirect-to?status_code=302&url=/get

###
GET https://httpbin.org/headers
Custom-header: hello=world

